services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA="Y"
      - MSSQL_SA_PASSWORD=Password@1
    ports:
      - "1433:1433"